# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=205),
        ),
    ]
