# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_url',
            new_name='image',
        ),
    ]
