# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 00:37
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20161225_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='portfolio/static/portfolio/images'),
        ),
    ]
