# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 18:28
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20170710_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='static/portfolio/images'),
        ),
    ]
